##############################################################################
#
# File: ci-arduinocli.yml
#
# Function:
#   YAML file specifying how to do continuous integration for Arduino-LMIC
#   (using arduino-cli)
#
##############################################################################

# the name that appears in the GitHub UI.
name: Arduino CI

# specify the events that trigger runs.
on:
  # pull requests (default settings)
  pull_request:
  # pushes (default settings)
  push:
  # repository operations
  repository_dispatch:
  schedule:
    # do a build once a week at 06:07Z Sunday
    - cron: '7 6 * * 0'
  
# what to do:
jobs:
  env:
    MCCI_CI_LIBRARY:  libraries/arduino-lmic
  
  # define a job named "arduinocli"
  arduinocli:
    # select a target OS
    runs-on:  ubuntu-latest
    name: ${{env.MCCI_CI_LIBRARY}} ${{matrix.arch}}

    strategy:
      matrix:
        arch: samd stm32 esp32 avr

    # step-by-step
    steps:
      # check out this repo as {root}/arduino-lmic
      - uses: actions/checkout@v2
        name: Check out the repo
        with:
          repository: ${{env.MCCI_CI_LIBRARY}}

      - uses: actions/checkout@v2
        name: Set up mcci-catena-ci
        with:
          repository: mcci-catena/mcci-catena-ci
          path: mcci-catena-ci

      - name: set up
        run: bash mcci-catena-ci/setup.sh -l ${{env.MCCI_CI_LIBRARY}} --arch ${{matrix.arch}}

      - name: Display structure of checkout
        run: tree -d $(realpath .)

#      - name: compile
#        run: bash mcci-catena-ci/arduino-regress-wrap.sh ${{env.MCCI_CI_LIBRARY}}

### end of file ###
